[package]
name = "firaw-ssh"
version = "0.4.0"
edition = "2021"
description = "Cliente SSH e SFTP da Firawynix"

[lib]
name = "firaw_ssh_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-notification = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ssh2 = { version = "0.9.6", features = ["openssl-on-win32", "vendored-openssl"] }
base64 = "0.22"
sha2 = "0.10"
uuid = { version = "1", features = ["v4"] }
interprocess = "2.4.4"
aes-gcm = "0.10"
argon2 = "0.5"

[target.'cfg(windows)'.dependencies]
keyring = { version = "3.6", features = ["windows-native"] }

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { version = "3.6", features = ["linux-native-sync-persistent", "crypto-rust"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
