import { KeyRound, LockKeyhole, Plus, Save, ShieldCheck, Star, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { api, readableError, type Profile, type TunnelRule } from './api';

type Section = 'login'|'options'|'terminal'|'sftp'|'tunnels'|'rdp'|'log';
const sections: Array<[Section,string]> = [['login','Login'],['options','Opções'],['terminal','Terminal'],['sftp','SFTP'],['tunnels','Encaminhamentos'],['rdp','Área de trabalho'],['log','Log']];

export default function ProfileEditor({ profile, profiles, onChange, password, passphrase, onPassword, onPassphrase, savePassword, savePassphrase, setSavePassword, setSavePassphrase, onSave, onConnect, busy, log }: {
  profile: Profile; profiles: Profile[]; onChange: (p: Profile)=>void; password:string; passphrase:string; onPassword:(v:string)=>void; onPassphrase:(v:string)=>void;
  savePassword:boolean; savePassphrase:boolean; setSavePassword:(v:boolean)=>void; setSavePassphrase:(v:boolean)=>void;
  onSave:()=>Promise<Profile|undefined>; onConnect:()=>void; busy:boolean; log:string[];
}) {
  const [section,setSection]=useState<Section>('login');
  const [serviceMessage,setServiceMessage]=useState('');
  const set = <K extends keyof Profile>(key:K,value:Profile[K])=>onChange({...profile,[key]:value});
  const addTunnel=()=>set('tunnels',[...profile.tunnels,{name:'Novo túnel',kind:'local',listenHost:'127.0.0.1',listenPort:8080,targetHost:'127.0.0.1',targetPort:80,enabled:true}]);
  const patchTunnel=(i:number, patch:Partial<TunnelRule>)=>set('tunnels',profile.tunnels.map((r,n)=>n===i?{...r,...patch}:r));
  return <section className="editor">
    <div className="editor-top">
      <div><small>PERFIL DE CONEXÃO</small><h1>{profile.name || 'Novo servidor'}</h1><p>{profile.host ? `${profile.username || 'usuário'}@${profile.host}:${profile.port}` : 'Configure os dados para começar'}</p></div>
      <div className="editor-actions"><button className={`star-button ${profile.favorite?'on':''}`} onClick={()=>set('favorite',!profile.favorite)} title="Favorito"><Star size={18} fill={profile.favorite?'currentColor':'none'}/></button><button className="btn secondary" onClick={onSave}><Save size={16}/>Salvar</button><button className="btn primary" disabled={busy} onClick={onConnect}>{busy?'Conectando…':'Conectar'}</button></div>
    </div>
    <nav className="tabs">{sections.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>{setSection(id);setServiceMessage('')}}>{label}</button>)}</nav>
    <div className="form-area">
      {section==='login' && <>
        <Panel title="Servidor" subtitle="Destino da conexão SSH">
          <div className="grid three"><Field label="Nome do perfil"><input value={profile.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Servidor / IP" wide><input value={profile.host} onChange={e=>set('host',e.target.value)} placeholder="exemplo.com ou 192.168.1.10"/></Field><Field label="Porta"><input type="number" min="1" max="65535" value={profile.port} onChange={e=>set('port',Number(e.target.value))}/></Field></div>
          <div className="grid two"><Field label="Usuário"><input value={profile.username} onChange={e=>set('username',e.target.value)} placeholder="root"/></Field><Field label="Cor do perfil"><div className="color-field"><input type="color" value={profile.color} onChange={e=>set('color',e.target.value)}/><span>{profile.color}</span></div></Field></div>
        </Panel>
        <Panel title="Autenticação" subtitle="Escolha como provar sua identidade">
          <div className="segmented">{([['password','Senha'],['key','Chave privada'],['agent','Agente SSH']] as const).map(([id,label])=><button className={profile.authMethod===id?'active':''} onClick={()=>set('authMethod',id)} key={id}>{id==='password'?<LockKeyhole size={16}/>:<KeyRound size={16}/>} {label}</button>)}</div>
          {profile.authMethod==='password' && <div className="credential-box"><Field label={profile.hasPassword?'Nova senha (deixe vazio para manter)':'Senha'}><input type="password" value={password} onChange={e=>onPassword(e.target.value)} placeholder={profile.hasPassword?'••••••••••••':'Digite a senha'}/></Field><Check checked={savePassword} onChange={setSavePassword} label="Salvar no cofre seguro do sistema" detail="Nunca é gravada no arquivo do perfil."/></div>}
          {profile.authMethod==='key' && <div className="key-auth-grid"><div className="key-file"><Field label="Chave privada ou arquivo .pub correspondente"><div className="input-action"><input value={profile.keyPath} readOnly placeholder="Selecione a chave sem extensão ou o .pub…"/><button onClick={async()=>{const p=await api.chooseKeyFile();if(p)set('keyPath',p)}}>Procurar</button></div></Field></div><div className="secret-card"><Check checked={profile.keyPassphraseEnabled} onChange={v=>{set('keyPassphraseEnabled',v);if(!v){onPassphrase('');setSavePassphrase(false)}}} label="Esta chave possui senha" detail="Ative apenas quando a chave privada for protegida."/>{profile.keyPassphraseEnabled&&<><Field label={profile.hasPassphrase?'Nova senha da chave (vazio mantém)':'Senha da chave privada'}><input type="password" value={passphrase} onChange={e=>onPassphrase(e.target.value)} placeholder={profile.hasPassphrase?'••••••••••••':'Desbloqueia o arquivo da chave'}/></Field><Check checked={savePassphrase} onChange={setSavePassphrase} label="Salvar senha da chave" detail="Protegida no Cofre do Windows."/></>}</div><div className="secret-card"><Check checked={profile.accountPasswordEnabled} onChange={v=>{set('accountPasswordEnabled',v);if(!v){onPassword('');setSavePassword(false)}}} label={`Servidor exige senha de ${profile.username||'root'}`} detail="Segunda etapa depois da chave."/>{profile.accountPasswordEnabled&&<><Field label={profile.hasPassword?`Nova senha de ${profile.username||'root'} (vazio mantém)`: `Senha de ${profile.username||'root'} — segunda etapa`}><input type="password" value={password} onChange={e=>onPassword(e.target.value)} placeholder={profile.hasPassword?'••••••••••••':'Senha da conta no servidor'}/></Field><Check checked={savePassword} onChange={setSavePassword} label={`Salvar senha de ${profile.username||'root'}`} detail="Usada somente quando o servidor solicitar."/></>}</div><div className="info key-auth-note"><ShieldCheck size={18}/><span>As duas etapas são independentes. Desative a senha da chave ou a senha da conta quando o seu servidor não utilizar uma delas. O arquivo <strong>.pub</strong> é convertido para a chave privada irmã automaticamente.</span></div></div>}
          {profile.authMethod==='agent' && <div className="info"><ShieldCheck size={18}/><span>O Firaw SSH tentará as chaves disponíveis no OpenSSH Agent do Windows.</span></div>}
        </Panel>
        {profile.hostKeySha256 && <Panel title="Identidade do servidor" subtitle="Chave confirmada na primeira conexão"><code className="fingerprint">{profile.hostKeySha256}</code></Panel>}
      </>}
      {section==='options' && <>
        <Panel title="Conexão" subtitle="Comportamento da sessão"><div className="grid two"><Field label="Keep-alive (segundos)"><input type="number" min="0" value={profile.keepAlive} onChange={e=>set('keepAlive',Number(e.target.value))}/></Field><Field label="Caminho da conexão"><select value={profile.proxyType} onChange={e=>set('proxyType',e.target.value)}><option value="none">Direta</option><option value="socks5">Proxy SOCKS5</option><option value="http">Proxy HTTP CONNECT</option><option value="ssh">Por outro perfil SSH</option></select></Field></div>{(profile.proxyType==='http'||profile.proxyType==='socks5')&&<div className="grid two"><Field label="Servidor do proxy"><input value={profile.proxyHost} onChange={e=>set('proxyHost',e.target.value)} placeholder="127.0.0.1"/></Field><Field label="Porta do proxy"><input type="number" min="1" max="65535" value={profile.proxyPort} onChange={e=>set('proxyPort',Number(e.target.value))}/></Field></div>}{profile.proxyType==='ssh'&&<Field label="Perfil intermediário"><select value={profile.proxyProfileId} onChange={e=>set('proxyProfileId',e.target.value)}><option value="">Escolha um servidor…</option>{profiles.filter(p=>p.id&&p.id!==profile.id).map(p=><option key={p.id} value={p.id}>{p.name} · {p.username}@{p.host}</option>)}</select></Field>}<Check checked={profile.autoReconnect} onChange={v=>set('autoReconnect',v)} label="Reconectar automaticamente" detail="Recupera a sessão quando a rede oscilar, com espera progressiva."/><Check checked={profile.compression} onChange={v=>set('compression',v)} label="Compressão SSH" detail="Útil em links lentos; pode gastar mais CPU."/></Panel>
        <Panel title="Serviços ao conectar" subtitle="O que fica disponível na sessão"><div className="checks-row"><Check checked={profile.terminalEnabled} onChange={v=>set('terminalEnabled',v)} label="Terminal"/><Check checked={profile.sftpEnabled} onChange={v=>set('sftpEnabled',v)} label="SFTP"/><Check checked={profile.rdpEnabled} onChange={v=>set('rdpEnabled',v)} label="Área de trabalho remota"/></div></Panel>
        <Panel title="Ponte segura para Codex e automações" subtitle="Autorização explícita deste perfil; credenciais nunca saem do Firaw SSH"><Check checked={profile.bridgeEnabled} onChange={v=>{set('bridgeEnabled',v);if(!v){set('bridgeAllowCommand',false);set('bridgeAllowSftp',false)}}} label="Autorizar este servidor na ponte local" detail="Somente programas neste computador podem pedir acesso; cada função é controlada abaixo."/>{profile.bridgeEnabled&&<div className="checks-row"><Check checked={profile.bridgeAllowCommand} onChange={v=>set('bridgeAllowCommand',v)} label="Permitir comandos" detail="Codex/Aion poderá executar comandos neste perfil."/><Check checked={profile.bridgeAllowSftp} onChange={v=>set('bridgeAllowSftp',v)} label="Permitir arquivos" detail="Permite enviar e baixar arquivos por SFTP."/></div>}<div className="info"><ShieldCheck size={18}/><span>A ponte identifica o perfil pelo cadastro e reutiliza o cofre seguro do sistema. Ela não entrega senha, senha da chave nem o conteúdo da chave privada ao solicitante.</span></div></Panel>
        <Panel title="Anotações" subtitle="Informações não sensíveis sobre este acesso"><textarea value={profile.notes} onChange={e=>set('notes',e.target.value)} placeholder="Ambiente, finalidade, observações…" rows={5}/></Panel>
      </>}
      {section==='terminal' && <>
        <Panel title="Emulação" subtitle="Compatível com servidores Linux, Unix e Windows"><div className="grid two"><Field label="Tipo de terminal"><select value={profile.terminalType} onChange={e=>set('terminalType',e.target.value)}><option>xterm-256color</option><option>xterm</option><option>vt100</option><option>ansi</option></select></Field><Field label="Pasta inicial"><input value={profile.initialDirectory} onChange={e=>set('initialDirectory',e.target.value)} placeholder="Ex.: /var/www (opcional)"/></Field></div></Panel>
        <Panel title="Editor externo" subtitle="Edite arquivos remotos e sincronize cada salvamento"><Check checked={profile.externalEditorEnabled} onChange={v=>set('externalEditorEnabled',v)} label="Abrir nano, vim e vi no editor externo" detail="O Firaw baixa uma cópia temporária, monitora o salvamento e devolve o arquivo ao servidor."/>{profile.externalEditorEnabled&&<Field label="Aplicativo do editor"><div className="input-action"><input value={profile.externalEditorPath} onChange={e=>set('externalEditorPath',e.target.value)} placeholder="Ex.: Notepad++ ou /usr/bin/kate"/><button onClick={async()=>{const p=await api.chooseEditorFile();if(p)set('externalEditorPath',p)}}>Procurar</button></div></Field>}<div className="info"><ShieldCheck size={18}/><span>Se o arquivo remoto mudar enquanto estiver aberto, o Firaw bloqueia a sobrescrita e avisa sobre o conflito.</span></div></Panel>
        <Panel title="Assistente de teclado" subtitle="Aparece automaticamente para nano, vim, less e outros programas"><div className="key-preview"><span><kbd>Ctrl</kbd>+<kbd>X</kbd> Sair</span><span><kbd>Ctrl</kbd>+<kbd>O</kbd> Salvar</span><span><kbd>Alt</kbd>+<kbd>U</kbd> Desfazer</span><span><kbd>Ctrl</kbd>+<kbd>W</kbd> Buscar</span></div><p className="muted">Os botões enviam as sequências reais ao servidor — não escrevem o texto “Ctrl+X”.</p></Panel>
      </>}
      {section==='sftp' && <><Panel title="Navegador SFTP" subtitle="Arquivos locais e remotos na mesma conexão"><Check checked={profile.sftpEnabled} onChange={v=>set('sftpEnabled',v)} label="Ativar SFTP neste perfil" detail="Envios e downloads podem ser pausados e retomados."/><Field label="Pasta remota inicial"><input value={profile.initialDirectory} onChange={e=>set('initialDirectory',e.target.value)} placeholder="Diretório pessoal quando vazio"/></Field></Panel><FeatureList items={['Navegação por pastas e ordenação','Pausar, continuar, cancelar e retomar','Tamanhos e permissões Unix legíveis','Identidade do servidor validada antes da transferência']}/></>}
      {section==='tunnels' && <>
        <Panel title="Encaminhamento de portas" subtitle="Local, remoto e SOCKS dinâmico"><div className="panel-title-action"><button className="btn secondary small" onClick={addTunnel}><Plus size={14}/>Adicionar regra</button></div>{profile.tunnels.length===0?<div className="blank-slate">Nenhum túnel configurado.</div>:profile.tunnels.map((r,i)=><div className="tunnel-row" key={i}><input className="tunnel-name" value={r.name} onChange={e=>patchTunnel(i,{name:e.target.value})}/><select value={r.kind} onChange={e=>patchTunnel(i,{kind:e.target.value as TunnelRule['kind']})}><option value="local">Local</option><option value="remote">Remoto</option><option value="dynamic">SOCKS</option></select><input value={r.listenHost} onChange={e=>patchTunnel(i,{listenHost:e.target.value})}/><input type="number" value={r.listenPort} onChange={e=>patchTunnel(i,{listenPort:Number(e.target.value)})}/><span>→</span><input value={r.targetHost} disabled={r.kind==='dynamic'} onChange={e=>patchTunnel(i,{targetHost:e.target.value})}/><input type="number" value={r.targetPort} disabled={r.kind==='dynamic'} onChange={e=>patchTunnel(i,{targetPort:Number(e.target.value)})}/><button className="icon danger" onClick={()=>set('tunnels',profile.tunnels.filter((_,n)=>n!==i))}><Trash2 size={15}/></button></div>)}</Panel>
        <div className="service-actions"><button className="btn primary" disabled={busy||profile.tunnels.every(r=>!r.enabled)} onClick={async()=>{setServiceMessage('');const saved=await onSave();if(!saved)return;try{const started=await api.startTunnels(saved.id,password||undefined,passphrase||undefined);setServiceMessage(started.length?started.map(t=>`${t.name}: ${t.listenHost}:${t.listenPort} → ${t.target}`).join(' · '):'Nenhum túnel habilitado.')}catch(e){setServiceMessage(readableError(e).message)}}}>Ativar túneis</button><button className="btn secondary" disabled={!profile.id} onClick={async()=>{try{await api.stopTunnels(profile.id);setServiceMessage('Túneis encerrados.')}catch(e){setServiceMessage(readableError(e).message)}}}>Parar túneis</button></div>
        {serviceMessage&&<div className="info service-message">{serviceMessage}</div>}
        <div className="info amber">Local abre uma porta neste PC; Remoto abre no servidor; SOCKS cria um proxy local que escolhe o destino a cada conexão.</div>
      </>}
      {section==='rdp' && <Panel title="Área de trabalho remota" subtitle="Acesso RDP protegido pelo túnel SSH"><Check checked={profile.rdpEnabled} onChange={v=>set('rdpEnabled',v)} label="Ativar Área de trabalho remota neste perfil"/><div className="grid two"><Field label="Computador visto pelo servidor"><input value={profile.rdpHost} onChange={e=>set('rdpHost',e.target.value)}/></Field><Field label="Porta RDP"><input type="number" value={profile.rdpPort} onChange={e=>set('rdpPort',Number(e.target.value))}/></Field></div><div className="service-actions"><button className="btn primary" disabled={busy||!profile.rdpEnabled} onClick={async()=>{setServiceMessage('');const saved=await onSave();if(!saved)return;try{const port=await api.openRdp(saved.id,password||undefined,passphrase||undefined);setServiceMessage(`Cliente RDP aberto pelo túnel seguro local 127.0.0.1:${port}.`)}catch(e){setServiceMessage(readableError(e).message)}}}>Abrir RDP seguro</button></div>{serviceMessage&&<div className="info service-message">{serviceMessage}</div>}<div className="info amber">O aplicativo cria uma porta local temporária pelo SSH e abre o cliente RDP do sistema.</div></Panel>}
      {section==='log' && <Panel title="Registro da sessão" subtitle="Eventos de conexão sem expor senhas"><div className="log-view" data-texto>{log.length?log.map((l,i)=><div key={i}>{l}</div>):<span>Nenhum evento nesta execução.</span>}</div></Panel>}
    </div>
  </section>;
}

function Panel({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}) { return <section className="panel"><div className="panel-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div></div>{children}</section> }
function Field({label,children,wide}:{label:string;children:React.ReactNode;wide?:boolean}) { return <label className={`field ${wide?'wide':''}`}><span>{label}</span>{children}</label> }
function Check({checked,onChange,label,detail}:{checked:boolean;onChange:(v:boolean)=>void;label:string;detail?:string}) { return <label className="check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i/><span><strong>{label}</strong>{detail&&<small>{detail}</small>}</span></label> }
function FeatureList({items}:{items:string[]}) { return <div className="feature-list">{items.map(x=><span key={x}><ShieldCheck size={15}/>{x}</span>)}</div> }
