import { listen } from '@tauri-apps/api/event';
import { ArrowDown, ArrowLeft, ArrowUp, File, FilePenLine, Folder, FolderOpen, Home, Monitor, Pause, Play, RefreshCw, Server, Upload, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { api, readableError, type LocalEntry, type Profile, type RemoteEntry, type TransferEvent } from './api';

export default function SftpView({profile,password,passphrase,onBack}:{profile:Profile;password?:string;passphrase?:string;onBack:()=>void}){
  const [remotePath,setRemotePath]=useState(profile.initialDirectory||'.');const [remoteItems,setRemoteItems]=useState<RemoteEntry[]>([]);const [remoteSelected,setRemoteSelected]=useState<string[]>([]);
  const [localPath,setLocalPath]=useState('');const [localItems,setLocalItems]=useState<LocalEntry[]>([]);const [localSelected,setLocalSelected]=useState<string[]>([]);
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [transfers,setTransfers]=useState<Record<string,TransferEvent>>({});const typeQuery=useRef('');const typeTimer=useRef<number>();
  const loadRemote=async(next=remotePath)=>{setBusy(true);setMessage('');try{setRemoteItems(await api.sftpList(profile.id,next,password,passphrase));setRemotePath(next);setRemoteSelected([])}catch(e){setMessage(readableError(e).message)}finally{setBusy(false)}};
  const loadLocal=async(next=localPath)=>{setMessage('');try{const list=await api.localList(next);setLocalItems(list);setLocalPath(next||(list[0]?parentLocal(list[0].path):''));setLocalSelected([])}catch(e){setMessage(readableError(e).message)}};
  useEffect(()=>{void loadLocal('');void loadRemote();const off=listen<TransferEvent>('transfer-progress',e=>{if(e.payload.profileId===profile.id)setTransfers(old=>({...old,[e.payload.transferId]:e.payload}))});return()=>{void off.then(fn=>fn())}},[]);
  const upload=async(paths=localSelected)=>{if(!paths.length)return;try{await api.sftpUploadPaths(profile.id,remotePath,paths,password,passphrase)}catch(e){setMessage(readableError(e).message)}};
  const download=async(paths=remoteSelected)=>{if(!paths.length)return;try{await api.sftpDownloadPaths(profile.id,paths,localPath,password,passphrase)}catch(e){setMessage(readableError(e).message)}};
  const chooseFiles=async()=>{const paths=await api.chooseLocalFiles();if(paths.length)await upload(paths)};const chooseFolder=async()=>{const path=await api.chooseLocalDirectory();if(path)await upload([path])};
  const transferAction=async(t:TransferEvent,action:'pause'|'resume'|'cancel')=>{try{if(action==='pause')await api.pauseTransfer(t.transferId);else if(action==='resume')await api.resumeTransfer(t.transferId);else await api.cancelTransfer(t.transferId);setTransfers(old=>({...old,[t.transferId]:{...t,status:action==='pause'?'paused':action==='resume'?'progress':'cancelled',message:action==='pause'?'Pausado':action==='resume'?'Continuando…':'Cancelando…'}}))}catch(e){setMessage(readableError(e).message)}};
  const select=(path:string,current:string[],setter:(v:string[])=>void,multi:boolean)=>setter(multi?(current.includes(path)?current.filter(x=>x!==path):[...current,path]):[path]);
  const typeSelect=(event:React.KeyboardEvent,items:Array<{name:string;path:string}>,setter:(v:string[])=>void)=>{if(event.ctrlKey||event.altKey||event.metaKey||event.key.length!==1)return;typeQuery.current+=event.key.toLowerCase();window.clearTimeout(typeTimer.current);typeTimer.current=window.setTimeout(()=>typeQuery.current='',800);const hit=items.find(x=>x.name.toLowerCase().startsWith(typeQuery.current));if(hit)setter([hit.path])};
  return <section className="sftp-page"><header className="terminal-header"><button className="icon" onClick={onBack}><ArrowLeft size={18}/></button><span className="server-icon" style={{'--profile-color':profile.color} as React.CSSProperties}><Folder size={17}/></span><div><strong>SFTP · {profile.name}</strong><small>{profile.username}@{profile.host} · arraste arquivos ou use os botões</small></div><div className="terminal-actions"><button className="btn secondary small" onClick={()=>void chooseFiles()}><Upload size={15}/>Selecionar arquivos</button><button className="btn secondary small" onClick={()=>void chooseFolder()}><FolderOpen size={15}/>Selecionar pasta</button><button className="btn secondary small" disabled={busy} onClick={()=>{void loadLocal();void loadRemote()}}><RefreshCw size={15}/>Atualizar</button></div></header>
    {message&&<div className="inline-error">{message}</div>}
    <div className="dual-sftp">
      <FilePane title="Meu PC" icon={<Monitor size={16}/>} path={localPath} setPath={setLocalPath} onGo={()=>void loadLocal(localPath)} onHome={()=>void loadLocal('')} onUp={()=>void loadLocal(parentLocal(localPath))} onKeyDown={e=>typeSelect(e,localItems,setLocalSelected)} onDrop={e=>{e.preventDefault();const paths=readDrag(e,'firaw-remote');if(paths.length)void download(paths)}}>
        {localItems.map(item=><FileRow key={item.path} name={item.name} directory={item.isDirectory} size={item.size} modified={item.modified} selected={localSelected.includes(item.path)} draggable onDragStart={e=>writeDrag(e,'firaw-local',localSelected.includes(item.path)?localSelected:[item.path])} onClick={e=>select(item.path,localSelected,setLocalSelected,e.ctrlKey)} onDoubleClick={()=>item.isDirectory&&void loadLocal(item.path)}/>) }
      </FilePane>
      <div className="transfer-controls"><button title="Enviar para o servidor" disabled={!localSelected.length} onClick={()=>void upload()}><ArrowUp size={18}/><span>Enviar</span></button><button title="Baixar para Meu PC" disabled={!remoteSelected.length} onClick={()=>void download()}><ArrowDown size={18}/><span>Baixar</span></button>{profile.externalEditorEnabled&&remoteSelected.length===1&&!remoteItems.find(x=>x.path===remoteSelected[0])?.isDirectory&&<button title="Editar e sincronizar" onClick={()=>void api.openRemoteEditor(profile.id,remoteSelected[0],password,passphrase).catch(e=>setMessage(readableError(e).message))}><FilePenLine size={18}/><span>Editar</span></button>}</div>
      <FilePane title={`Servidor · ${profile.name}`} icon={<Server size={16}/>} path={remotePath} setPath={setRemotePath} onGo={()=>void loadRemote(remotePath)} onHome={()=>void loadRemote(profile.initialDirectory||'.')} onUp={()=>void loadRemote(parentRemote(remotePath))} onKeyDown={e=>typeSelect(e,remoteItems,setRemoteSelected)} onDrop={e=>{e.preventDefault();const paths=readDrag(e,'firaw-local');if(paths.length)void upload(paths)}}>
        {remoteItems.map(item=><FileRow key={item.path} name={item.name} directory={item.isDirectory} size={item.size} modified={item.modified} permissions={item.permissions} selected={remoteSelected.includes(item.path)} draggable onDragStart={e=>writeDrag(e,'firaw-remote',remoteSelected.includes(item.path)?remoteSelected:[item.path])} onClick={e=>select(item.path,remoteSelected,setRemoteSelected,e.ctrlKey)} onDoubleClick={()=>item.isDirectory&&void loadRemote(item.path)}/>) }
      </FilePane>
    </div>
    {Object.keys(transfers).length>0&&<div className="transfer-tray">{Object.values(transfers).slice(-4).map(t=><div key={t.transferId} className={t.status}><span>{t.direction==='upload'?'↑':'↓'} {t.item}</span><small>{t.message}</small><div className="transfer-buttons">{!['completed','failed','cancelled'].includes(t.status)&&<>{t.status==='paused'?<button title="Continuar" onClick={()=>void transferAction(t,'resume')}><Play size={12}/></button>:<button title="Pausar" onClick={()=>void transferAction(t,'pause')}><Pause size={12}/></button>}<button title="Cancelar" onClick={()=>void transferAction(t,'cancel')}><X size={12}/></button></>}</div><progress max={Math.max(t.total,1)} value={t.completed}/></div>)}</div>}
  </section>;
}

function FilePane({title,icon,path,setPath,onGo,onHome,onUp,onKeyDown,onDrop,children}:{title:string;icon:React.ReactNode;path:string;setPath:(v:string)=>void;onGo:()=>void;onHome:()=>void;onUp:()=>void;onKeyDown:(e:React.KeyboardEvent)=>void;onDrop:(e:React.DragEvent)=>void;children:React.ReactNode}){return <section className="file-pane" tabIndex={0} onKeyDown={onKeyDown} onDragOver={e=>e.preventDefault()} onDrop={onDrop}><header>{icon}<strong>{title}</strong><small>digite uma letra para localizar</small></header><div className="pane-path"><button className="icon" onClick={onHome}><Home size={14}/></button><button className="icon" onClick={onUp}><ArrowLeft size={14}/></button><input value={path} onChange={e=>setPath(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.stopPropagation();onGo()}}}/><button className="btn primary small" onClick={onGo}>Ir</button></div><div className="pane-list"><div className="pane-head"><span>Nome</span><span>Tamanho</span><span>Modificado</span><span>Permissões</span></div>{children}</div></section>}
function FileRow({name,directory,size,modified,permissions,selected,...events}:{name:string;directory:boolean;size:number;modified:number;permissions?:number;selected:boolean;draggable?:boolean;onDragStart?:(e:React.DragEvent)=>void;onClick?:(e:React.MouseEvent)=>void;onDoubleClick?:()=>void}){return <div className={`pane-row ${selected?'selected':''}`} {...events}><span>{directory?<Folder size={16}/>:<File size={16}/>}<strong>{name}</strong></span><span>{directory?'—':formatSize(size)}</span><span>{modified?new Date(modified*1000).toLocaleString():'—'}</span><code>{permissions?`0${(permissions&0o777).toString(8)}`:'—'}</code></div>}
function writeDrag(e:React.DragEvent,type:string,paths:string[]){e.dataTransfer.setData(`application/${type}`,JSON.stringify(paths));e.dataTransfer.effectAllowed='copy'}
function readDrag(e:React.DragEvent,type:string){try{return JSON.parse(e.dataTransfer.getData(`application/${type}`)||'[]') as string[]}catch{return[]}}
const parentRemote=(p:string)=>{const x=p.replace(/\\/g,'/').replace(/\/$/,'');return x.slice(0,x.lastIndexOf('/'))||'/'};
const parentLocal=(p:string)=>{const normalized=p.replace(/[\\/]$/,'');const i=Math.max(normalized.lastIndexOf('\\'),normalized.lastIndexOf('/'));return i>2?normalized.slice(0,i):normalized.slice(0,3)};
const formatSize=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:n<1073741824?`${(n/1048576).toFixed(1)} MB`:`${(n/1073741824).toFixed(1)} GB`;
