import { FitAddon } from '@xterm/addon-fit';
import { Terminal } from '@xterm/xterm';
import { listen } from '@tauri-apps/api/event';
import { ArrowLeft, Clipboard, FilePenLine, Keyboard, PlugZap, Power, RotateCcw, Search, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { api, readableError, type ExternalEditEvent, type Profile, type TerminalOutput, type TerminalStatus } from './api';
import { extractNanoPath, normalizeRemoteEditorInput, trackExternalEditorInput } from './editorInput';

type Helper = 'shell'|'nano'|'vim'|'less';
type Shortcut = {label:string;hint:string;command:string;data:string};
export type TerminalTabInfo = {id:string;profile:Profile};

const KEYS: Record<Helper,Shortcut[]> = {
  shell:[{label:'Ctrl+C',hint:'Interromper',command:'SIGINT',data:'\x03'},{label:'Ctrl+L',hint:'Limpar',command:'clear-screen',data:'\x0c'},{label:'Ctrl+D',hint:'Sair',command:'EOF',data:'\x04'},{label:'Tab',hint:'Completar',command:'TAB',data:'\t'},{label:'↑',hint:'Anterior',command:'history-prev',data:'\x1b[A'}],
  nano:[{label:'Ctrl+O',hint:'Salvar',command:'^O Write Out',data:'\x0f'},{label:'Ctrl+X',hint:'Sair',command:'^X Exit',data:'\x18'},{label:'Ctrl+W',hint:'Buscar',command:'^W Where Is',data:'\x17'},{label:'Ctrl+K',hint:'Recortar',command:'^K Cut',data:'\x0b'},{label:'Ctrl+U',hint:'Colar',command:'^U Paste',data:'\x15'},{label:'Alt+U',hint:'Desfazer',command:'M-U Undo',data:'\x1bu'},{label:'Alt+E',hint:'Refazer',command:'M-E Redo',data:'\x1be'}],
  vim:[{label:'Esc',hint:'Modo normal',command:'ESC',data:'\x1b'},{label:':w',hint:'Salvar',command:':write',data:':w\r'},{label:':q',hint:'Sair',command:':quit',data:':q\r'},{label:':wq',hint:'Salvar e sair',command:':wq',data:':wq\r'},{label:'u',hint:'Desfazer',command:'undo',data:'u'},{label:'Ctrl+R',hint:'Refazer',command:'redo',data:'\x12'},{label:'/',hint:'Buscar',command:'/pattern',data:'/'}],
  less:[{label:'q',hint:'Sair',command:'quit',data:'q'},{label:'/',hint:'Buscar',command:'/pattern',data:'/'},{label:'n',hint:'Próximo',command:'next match',data:'n'},{label:'g',hint:'Início',command:'first line',data:'g'},{label:'G',hint:'Fim',command:'last line',data:'G'},{label:'Espaço',hint:'Página',command:'page down',data:' '}],
};

const encode = (text:string) => {const bytes=new TextEncoder().encode(text);let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));return btoa(binary)};
const decode = (text:string) => Uint8Array.from(atob(text), c=>c.charCodeAt(0));
type Props = {tabId:string;profile:Profile;password?:string;passphrase?:string;initialError?:string;isActive:boolean;tabs:TerminalTabInfo[];onSelectTab:(id:string)=>void;onCloseTab:(id:string)=>void;onNewTab:()=>void;onBack:()=>void;onLog:(s:string)=>void};

export default function TerminalView({tabId,profile,password,passphrase,initialError,isActive,tabs,onSelectTab,onCloseTab,onNewTab,onBack,onLog}:Props) {
  const holder=useRef<HTMLDivElement>(null);const terminal=useRef<Terminal>();const fit=useRef<FitAddon>();const sessionId=useRef<string>();const sample=useRef('');const line=useRef('');const inputEscapeState=useRef<0|1|2>(0);const shellMode=useRef(true);const externalOpening=useRef('');
  const [status,setStatus]=useState<'idle'|'connecting'|'connected'|'disconnected'|'error'>('idle');const [message,setMessage]=useState(initialError||'Pronto para conectar');const [helper,setHelper]=useState<Helper>('shell');const [showKeys,setShowKeys]=useState(true);const [lastBackup,setLastBackup]=useState('');
  useEffect(()=>{shellMode.current=helper==='shell'},[helper]);
  useEffect(()=>{if(isActive)setTimeout(()=>{try{fit.current?.fit();terminal.current?.focus()}catch{}},30)},[isActive,showKeys]);
  useEffect(()=>{
    if(!holder.current)return;
    const term=new Terminal({fontFamily:'Cascadia Code, Consolas, monospace',fontSize:14,lineHeight:1.2,cursorBlink:true,scrollback:12000,allowTransparency:true,theme:{background:'#05080d',foreground:'#dbeafe',cursor:'#22d3ee',selectionBackground:'#164e63aa',black:'#0b1018',red:'#fb7185',green:'#34d399',yellow:'#fbbf24',blue:'#60a5fa',magenta:'#c084fc',cyan:'#22d3ee',white:'#e2e8f0',brightBlack:'#64748b',brightRed:'#fda4af',brightGreen:'#6ee7b7',brightYellow:'#fde68a',brightBlue:'#93c5fd',brightMagenta:'#d8b4fe',brightCyan:'#67e8f9',brightWhite:'#ffffff'}});
    const fitter=new FitAddon();term.loadAddon(fitter);term.open(holder.current);fitter.fit();term.focus();terminal.current=term;fit.current=fitter;term.writeln('\x1b[38;2;34;211;238m  Firaw SSH\x1b[0m  terminal seguro e assistido');term.writeln('\x1b[38;2;100;116;139m  Cores ANSI/True Color ativas. As teclas rápidas enviam sequências reais.\x1b[0m\r\n');
    const data=term.onData(routeTerminalInput);
    const resize=term.onResize(({cols,rows})=>{if(sessionId.current)void api.terminalResize(sessionId.current,cols,rows)});const observer=new ResizeObserver(()=>{try{fitter.fit()}catch{}});observer.observe(holder.current);
    const offOutput=listen<TerminalOutput>('terminal-output',e=>{if(e.payload.sessionId!==sessionId.current)return;const bytes=decode(e.payload.data);term.write(bytes,()=>{if(!profile.externalEditorEnabled||externalOpening.current)return;const remotePath=detectVisibleEditorPath(term);if(remotePath)launchExternalEditor(remotePath,true)});const plain=new TextDecoder().decode(bytes).replace(/\x1b\[[0-9;?]*[ -/]*[@-~]/g,'');sample.current=(sample.current+plain).slice(-4000);detect(sample.current,setHelper)});
    const offStatus=listen<TerminalStatus>('terminal-status',e=>{if(e.payload.sessionId!==sessionId.current)return;let msg=e.payload.message;if(e.payload.status==='error'){const parsed=readableError(msg);msg=parsed.message;term.writeln(`\r\n\x1b[38;2;251;113;133m${msg}\x1b[0m`)}setStatus(e.payload.status);setMessage(msg);onLog(`${new Date().toLocaleTimeString()} · ${profile.name}: ${msg}`)});
    const offEdit=listen<ExternalEditEvent>('external-edit-status',e=>{if(e.payload.profileId!==profile.id)return;if(e.payload.status==='closed'||e.payload.status==='failed')externalOpening.current='';if(e.payload.status==='saved')setLastBackup(e.payload.remotePath);const color=e.payload.status==='failed'||e.payload.status==='conflict'?'251;113;133':e.payload.status==='saved'?'52;211;153':'34;211;238';term.writeln(`\r\n\x1b[38;2;${color}m[Editor externo] ${e.payload.message}\x1b[0m`)});
    void Promise.all([offOutput,offStatus,offEdit]).then(()=>connect());return()=>{observer.disconnect();data.dispose();resize.dispose();void offOutput.then(fn=>fn());void offStatus.then(fn=>fn());void offEdit.then(fn=>fn());if(sessionId.current)void api.disconnectTerminal(sessionId.current);term.dispose()};
  },[]);
  async function connect(){try{setStatus('connecting');setMessage('Abrindo conexão segura…');const t=terminal.current!;sessionId.current=await api.connectTerminal(profile.id,t.cols,t.rows,password,passphrase)}catch(e){const err=readableError(e);setStatus('error');setMessage(err.message);terminal.current?.writeln(`\r\n\x1b[38;2;251;113;133m${err.message}\x1b[0m`)}}
  function launchExternalEditor(remotePath:string,exitTerminalEditor=false){const path=remotePath.trim();if(!path||externalOpening.current===path)return;externalOpening.current=path;if(exitTerminalEditor&&sessionId.current)void api.terminalInput(sessionId.current,encode('\x18'));terminal.current?.writeln(`\r\n\x1b[38;2;34;211;238mAbrindo ${path} no editor externo…\x1b[0m`);void api.openRemoteEditor(profile.id,path,password,passphrase).catch(e=>{externalOpening.current='';const message=readableError(e).message;setMessage(message);terminal.current?.writeln(`\r\n\x1b[38;2;251;113;133m${message}\x1b[0m`)})}
  function routeTerminalInput(text:string){if(!sessionId.current)return;let outgoing=text;if(shellMode.current&&profile.externalEditorEnabled){const tracked=trackExternalEditorInput(text,{line:line.current,escapeState:inputEscapeState.current});line.current=tracked.line;inputEscapeState.current=tracked.escapeState;outgoing=tracked.outgoing;for(const remotePath of tracked.targets)launchExternalEditor(remotePath)}void api.terminalInput(sessionId.current,encode(outgoing))}
  const disconnect=async()=>{if(sessionId.current)await api.disconnectTerminal(sessionId.current);sessionId.current=undefined;setStatus('disconnected');setMessage('Sessão encerrada.')};const send=(data:string)=>{routeTerminalInput(data);terminal.current?.focus()};const editPath=()=>{const suggestion=detectVisibleEditorPath(terminal.current);const input=prompt('Cole o caminho remoto ou o comando completo (ex.: nano /home/arquivo):',suggestion||'');if(!input)return;const remotePath=normalizeRemoteEditorInput(input);if(remotePath)launchExternalEditor(remotePath,Boolean(suggestion))};
  return <section className={`terminal-page terminal-session ${isActive?'visible':'hidden'}`}><header className="terminal-header"><button className="icon" onClick={onBack}><ArrowLeft size={18}/></button><span className="server-icon" style={{'--profile-color':profile.color} as React.CSSProperties}><PlugZap size={17}/></span><div><strong>{profile.name}</strong><small>{profile.username}@{profile.host}:{profile.port}</small></div><span className={`status ${status}`}><i/>{message}</span><div className="terminal-actions">{lastBackup&&<button className="btn secondary small" title={lastBackup} onClick={()=>{if(confirm(`Restaurar a versão anterior de ${lastBackup}?`))void api.restoreEditorBackup(profile.id,lastBackup,password,passphrase).then(msg=>terminal.current?.writeln(`\r\n\x1b[38;2;52;211;153m${msg}\x1b[0m`)).catch(e=>setMessage(readableError(e).message))}}><RotateCcw size={15}/>Desfazer envio</button>}{profile.externalEditorEnabled&&<button className="btn secondary small" onClick={editPath}><FilePenLine size={15}/>Editor externo</button>}<button className={`btn secondary small ${showKeys?'selected':''}`} onClick={()=>setShowKeys(v=>!v)}><Keyboard size={15}/>Teclas</button>{status==='connected'?<button className="btn danger small" onClick={()=>void disconnect()}><Power size={15}/>Desconectar</button>:<button className="btn primary small" disabled={status==='connecting'} onClick={()=>void connect()}><PlugZap size={15}/>Conectar</button>}</div></header>
    <div className="terminal-tabs">{tabs.map(tab=><button key={tab.id} className={tab.id===tabId?'active':''} onClick={()=>onSelectTab(tab.id)}><span className="dot" style={{background:tab.profile.color}}/><span>{tab.profile.name}</span><X size={13} onClick={e=>{e.stopPropagation();onCloseTab(tab.id)}}/></button>)}<button className="new-tab" title="Nova sessão" onClick={onNewTab}>+</button></div><div className="terminal-holder" ref={holder}/>{showKeys&&<div className="key-helper"><div className="helper-label"><Keyboard size={16}/><span><strong>{helper==='nano'?'GNU nano':helper==='vim'?'Vim':helper==='less'?'Visualizador less':'Shell'}</strong><small>teclas reais</small></span></div><div className="shortcut-scroll">{KEYS[helper].map(k=><button key={k.label} onClick={()=>send(k.data)}><kbd>{k.label}</kbd><span>{k.hint}</span><small>{k.command}</small></button>)}</div><button className="icon" title="Colar" onClick={async()=>{try{send(await navigator.clipboard.readText())}catch{}}}><Clipboard size={16}/></button><button className="icon" title="Selecionar saída" onClick={()=>terminal.current?.selectAll()}><Search size={16}/></button></div>}</section>;
}
function detectVisibleEditorPath(term?:Terminal){if(!term)return '';const buffer=term.buffer.active;const start=Math.max(0,buffer.length-term.rows-4);for(let index=buffer.length-1;index>=start;index--){const text=buffer.getLine(index)?.translateToString(true)||'';const path=extractNanoPath(text);if(path)return path}return ''}
function detect(text:string,set:(h:Helper)=>void){const t=text.toLowerCase();if(t.includes('gnu nano')||t.includes('^g help')||t.includes('^x exit'))set('nano');else if(t.includes('-- more --')||t.includes('(end)'))set('less');else if(t.includes('vim')||t.includes('recording @')||t.includes('-- insert --'))set('vim');else if(/[#$>]\s?$/.test(t.trimEnd().slice(-3)))set('shell')}
